services:
    _defaults:
        autowire: true      
        autoconfigure: true 

    Alumni\ActuatorBundle\Controller\:
        resource: '../../Controller'
        tags: ['controller.service_arguments']