services:
#   OsOliver\OpenSearchMatViewBundle\Service\OpenSearchMatViewService:
#     class: OsOliver\OpenSearchMatViewBundle\Service\OpenSearchMatViewService
#     public: true
#     autowire: true
    _defaults:
        autowire: true
        autoconfigure: true